# Generated by Django 5.1.1 on 2025-01-08 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0021_delete_motivational_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivational_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Мотивационное сообщения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivational_messages', to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Мотивационное сообщение',
                'verbose_name_plural': 'Мотивационные сообщения',
            },
        ),
    ]
