# Generated by Django 5.1.1 on 2025-01-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivational_messages',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
