# Generated by Django 5.1.1 on 2025-01-08 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_motivational_messages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivational_messages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 16, 19, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
