# Generated by Django 5.1.1 on 2024-12-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_bot_message_anyway_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Гендр'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='massa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выбранная цель'),
        ),
    ]
