# Generated by Django 5.1.1 on 2024-12-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_botuser_age_botuser_gender_botuser_massa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Наличие аллергии'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='age',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='gender',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Гендр'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='massa',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='purpose',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Выбранная цель'),
        ),
    ]
