# Generated by Django 5.1.1 on 2024-12-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_botuser_last_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='protein',
            field=models.TextField(blank=True, null=True, verbose_name='Категория протеина исходя из цели'),
        ),
    ]
