# Generated by Django 5.1.1 on 2024-12-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_botuser_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='training_frequency',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Частота тренировок в неделю'),
        ),
    ]
