# Generated by Django 5.1.1 on 2025-01-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_text_castom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text_castom',
            options={'verbose_name': 'Редактор текстовок', 'verbose_name_plural': 'Редактор текстовок'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='council',
            field=models.TextField(blank=True, null=True, verbose_name='Последний совет'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='menu',
            field=models.TextField(blank=True, null=True, verbose_name='Меню'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscribe_data_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscribe_data_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscription',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписка'),
        ),
    ]
