# Generated by Django 5.1.1 on 2025-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_text_castom_options_botuser_council_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='height',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Рост'),
        ),
    ]
