# Generated by Django 5.1.1 on 2025-01-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_botuser_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.TextField(verbose_name='id заявки')),
                ('status', models.CharField(max_length=255, verbose_name='статус оплаты')),
                ('user_id', models.CharField(max_length=255, verbose_name='id пользоователя')),
            ],
        ),
        migrations.AlterField(
            model_name='botuser',
            name='height',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Рост (в см)'),
        ),
    ]
