# Generated by Django 5.1.1 on 2025-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_delete_motivational_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language_chooce',
            field=models.CharField(blank=True, choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=2, null=True, verbose_name='Выбор языка'),
        ),
    ]
