# Generated by Django 5.1.1 on 2025-01-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_uservalidip'),
        ('bot', '0023_alter_botuser_language_chooce'),
    ]

    operations = [
    ]
