# Generated by Django 5.1.1 on 2025-01-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_merge_20250110_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot_commands',
            options={'verbose_name': 'Команду / reply кнопку', 'verbose_name_plural': 'Команды / reply кнопки'},
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='count_generation',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='format_photo',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='gender_first',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='interes',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='interes_first',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='negative_prompt',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='period',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='period_first',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='prompt_leonardo',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='summa',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='summa_first',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='type_investor',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='type_investor_first',
        ),
        migrations.AddField(
            model_name='botuser',
            name='temporary_training_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID временной тренировки'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='gender',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Гендр'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language_chooce',
            field=models.CharField(blank=True, choices=[('ru', 'ru'), ('en', 'en')], max_length=4, null=True, verbose_name='Выбор языка'),
        ),
        migrations.CreateModel(
            name='UserTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_traning', models.TextField(blank=True, null=True, verbose_name='Название тренировки')),
                ('training_data', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения тренировки')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус отправки уведа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertraining', to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Тренировку',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.DeleteModel(
            name='UserValidIP',
        ),
    ]
